# Basisconfiguratie voor Home Assistant
default_config:

# Home Assistant basisinstellingen, met gebruik van secrets.yaml
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  currency: EUR
  time_zone: Europe/Amsterdam
  external_url: !secret external_url


# Reverse proxy ondersteuning via Kubernetes Gateway (Cilium)
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 10.0.0.0/8
  - 127.0.0.1
  - ::1
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Bestandssplitsing (optioneel)
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
